name: AI PR Automation

on:
  pull_request:
    types: [opened, synchronize]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  # Analysis job - runs on PR open/update
  analyze:
    if: github.event_name == 'pull_request'
    uses: efrat-rabin/ai-monitoring/.github/workflows/analyze-pr-code.yml@main
    with:
      pr_number: ${{ github.event.pull_request.number }}
      repository: ${{ github.repository }}
      post_comment: true
    secrets:
      cursor_api_key: ${{ secrets.CURSOR_API_KEY }}

  # Apply job - runs on /apply-logs comment
  apply:
    if: |
      github.event_name == 'pull_request_review_comment' &&
      contains(github.event.comment.body, '/apply-logs')
    runs-on: ubuntu-latest
    steps:
      - name: Debug event
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Comment body: ${{ github.event.comment.body }}"
          echo "Comment ID: ${{ github.event.comment.id }}"
          echo "In reply to: ${{ github.event.comment.in_reply_to_id }}"
          echo "PR number: ${{ github.event.pull_request.number }}"

      - name: Checkout calling repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Checkout workflow repository
        uses: actions/checkout@v4
        with:
          repository: efrat-rabin/ai-monitoring
          path: .ai-monitoring
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd .ai-monitoring
          pip install -r requirements.txt

      - name: Check if apply should be triggered
        id: check_apply
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export PYTHONPATH="${PYTHONPATH}:${GITHUB_WORKSPACE}/.ai-monitoring/libs"
          
          # Get comment IDs from event context
          COMMENT_ID="${{ github.event.comment.id }}"
          IN_REPLY_TO_ID="${{ github.event.comment.in_reply_to_id }}"
          
          # Debug output
          echo "Comment ID from event: '$COMMENT_ID'"
          echo "In-reply-to ID from event: '$IN_REPLY_TO_ID'"
          
          # Validate we have comment_id
          if [ -z "$COMMENT_ID" ]; then
            echo "ERROR: comment.id is not available in the event context"
            echo "should_apply=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # If no in_reply_to_id, use comment_id itself
          if [ -z "$IN_REPLY_TO_ID" ]; then
            echo "No in_reply_to_id found, using comment_id as fallback"
            IN_REPLY_TO_ID="$COMMENT_ID"
          fi
          
          python .ai-monitoring/actions/apply-suggested-logs/check_apply_trigger.py \
            --pr-number ${{ github.event.pull_request.number }} \
            --repository ${{ github.repository }} \
            --comment-id "$COMMENT_ID" \
            --in-reply-to-id "$IN_REPLY_TO_ID"

      - name: Load parent comment
        if: steps.check_apply.outputs.should_apply == 'true'
        id: load_comment
        run: |
          PARENT_BODY=$(cat apply-trigger.json | jq -r '.parent_comment_body')
          echo "parent_body<<EOF" >> $GITHUB_OUTPUT
          echo "$PARENT_BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Apply patches
        if: steps.check_apply.outputs.should_apply == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export PYTHONPATH="${PYTHONPATH}:${GITHUB_WORKSPACE}/.ai-monitoring/libs"
          cd ${GITHUB_WORKSPACE}
          
          # Write parent comment to file
          cat > parent-comment.txt << 'COMMENT_EOF'
          ${{ steps.load_comment.outputs.parent_body }}
          COMMENT_EOF
          
          python .ai-monitoring/actions/apply-suggested-logs/main.py \
            --pr-number ${{ github.event.pull_request.number }} \
            --repository ${{ github.repository }} \
            --comment-body-file parent-comment.txt

      - name: Commit and push changes
        if: steps.check_apply.outputs.should_apply == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Apply AI-suggested logging improvements"
            git push
          fi

      - name: Post success comment
        if: steps.check_apply.outputs.should_apply == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export PYTHONPATH="${PYTHONPATH}:${GITHUB_WORKSPACE}/.ai-monitoring/libs"
          python .ai-monitoring/actions/apply-suggested-logs/post_apply_comment.py \
            --pr-number ${{ github.event.pull_request.number }} \
            --repository ${{ github.repository }} \
            --success true

