name: Apply Suggested Logs

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: false
        type: string
      repository:
        description: 'Repository (owner/repo)'
        required: false
        type: string
      git_token:
        description: 'GitHub Token'
        required: true
        type: string

jobs:
  apply-logs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Run apply suggested logs script
        run: python actions/apply-suggested-logs/main.py
        env:
          GITHUB_TOKEN: ${{ inputs.git_token }}
          PR_NUMBER: ${{ inputs.pr_number }}
          REPOSITORY: ${{ inputs.repository }}

