name: Orchestrator Example (Main Workflow)

# This is an example of how the main orchestrator workflow would work
# It combines analysis and apply workflows with comment monitoring

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  # Job 1: Run analysis when PR is opened/updated
  analyze:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/analyze-pr-code.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}
      repository: ${{ github.repository }}
      post_comment: true
      test_mode: true
    secrets:
      cursor_api_key: ${{ secrets.CURSOR_API_KEY }}
  
  # Job 2: Check for /apply-logs trigger in comments
  check-apply-trigger:
    if: |
      github.event_name == 'issue_comment' &&
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/apply-logs')
    runs-on: ubuntu-latest
    outputs:
      should_apply: ${{ steps.check.outputs.triggered }}
      comment_id: ${{ github.event.comment.id }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Check if trigger is valid
        id: check
        run: |
          # Check if comment contains /apply-logs
          if echo "${{ github.event.comment.body }}" | grep -q "/apply-logs"; then
            echo "triggered=true" >> $GITHUB_OUTPUT
            echo "✅ /apply-logs trigger detected"
          else
            echo "triggered=false" >> $GITHUB_OUTPUT
            echo "ℹ️  No /apply-logs trigger found"
          fi
  
  # Job 3: Get latest analysis results
  get-analysis-results:
    if: needs.check-apply-trigger.outputs.should_apply == 'true'
    needs: check-apply-trigger
    runs-on: ubuntu-latest
    outputs:
      analysis_results: ${{ steps.get-results.outputs.results }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Download latest analysis results
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: analyze-pr-code.yml
          name: analysis-results
          path: ./
          pr: ${{ github.event.issue.number }}
      
      - name: Read analysis results
        id: get-results
        run: |
          if [ -f analysis-results.json ]; then
            echo "results<<EOF" >> $GITHUB_OUTPUT
            cat analysis-results.json >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            echo "✅ Analysis results loaded"
          else
            echo "❌ No analysis results found"
            exit 1
          fi
  
  # Job 4: Apply logging improvements
  apply-logs:
    if: needs.check-apply-trigger.outputs.should_apply == 'true'
    needs: [check-apply-trigger, get-analysis-results]
    uses: ./.github/workflows/apply-suggested-logs.yml
    with:
      pr_number: ${{ github.event.issue.number }}
      repository: ${{ github.repository }}
      analysis_results: ${{ needs.get-analysis-results.outputs.analysis_results }}
      comment_id: ${{ needs.check-apply-trigger.outputs.comment_id }}
    secrets:
      git_token: ${{ secrets.BOT_GITHUB_TOKEN }}
      cursor_api_key: ${{ secrets.CURSOR_API_KEY }}

